Changed @choice from being created as a thread, to just being a simple callback. The thread functionality was not used anyway.
##############

Added support for actions written in strings. Was done by adding 10 lines to Alternation.execute()

@process
def par_reader(cin1,cin2,cin3,cin4, cnt, sleeper):
    while True:
        if sleeper: sleeper()
        Alternation(
            {
                cin1:"print '#',; print cin3(),; print '#',",
                cin2:"print 'id='+str(ChannelInput),",
                cin3:action(),
                cin4:action()
            }
        ).execute()

I have tried to create a decent syntax error..  Adding an error by writing ChannelInput as ChanWRONGInput, produces the following error:

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 522, in __bootstrap_inner
    self.run()
  File "/Users/runef/Desktop/NewPyCSP/pycsp/process.py", line 29, in run
    self.retval = self.fn(*self.args, **self.kwargs)
  File "_autotest.py", line 30, in par_reader
    cin4:action()
  File "/Users/runef/Desktop/NewPyCSP/pycsp/alternation.py", line 87, in execute
    exec(code, f_globals, f_locals)
  File "_autotest.py line 30 in string", line 1, in <module>
NameError: name 'ChanWRONGInput' is not defined


Notice that the first action
print '#',; print cin3(),; print '#'
actually reads from one of the other channels and is able to do this, because the namespace is inherited using the inspect module.