The following test shows that we update Channel.__class__ while a process is blocking on the channel.
_read2() fails because _read2_Channel requires 2 arguments and not one as _read2_ChannelOne2One

Rune-Mllegaard-Friborgs-MacBook-Pro:examples runef$ python switch_mode.py
Using version (0, 9, 0, 'dynamic')
_read1_ChannelOne2One
_read2_ChannelOne2One
Test
_read1_ChannelOne2One
Traceback (most recent call last):
  File "switch_mode.py", line 20, in <module>
    cout2('Test2')
  File "../pycsp/channel.py", line 143, in _write
    self.internal['reader'].greenlet.switch()                    
  File "../pycsp/process.py", line 96, in run
    self.fn(*self.args, **self.kwargs)
  File "switch_mode.py", line 8, in Fun
    print cin()
  File "../pycsp/channel.py", line 85, in _read
    return self._read2()
TypeError: _read2() takes exactly 2 arguments (1 given)